server:
  port: 8080
spring:
  servlet:
    multipart:
      max-file-size: 1000GB
      max-request-size: 1000GB
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://124.223.187.100:3306/teee_db
    username: TEEE
    password: teee123456
path:
  picPath: /usr/local/myPic
  filePath: /usr/local/myFile
  facePath: /usr/local/myFace
  tempPath: /usr/local/myTemp
logging:
  level:
    root: info
  file:
    name: /usr/local/TEEELog/log.log
#path:
#  picPath: D:/testpic/
#  filePath: D:/testfile/
#  facePath: D:/testFace/
realMaxFileSizeMB: 50
Tencent:
  secretId: AKIDjU6ZMxWiookaLzXjrsjPtAIG3hEbopWE
  secretKey: gHi5LQwKWbTAh3DD2YtAFAvY5RcdVBi3
#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl